---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-public
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-node-lease
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ingress
automountServiceAccountToken: false
