---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-public
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-node-lease
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ingress
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: external-secrets
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kyverno-reporter
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: istio-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: oracle
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: panchito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: rigoberta
automountServiceAccountToken: false
