---                                                                                                                                   
apiVersion: v1                  
kind: Namespace                
metadata:                                                         
  name: platform                                                  
  labels:                                                                                                                             
    name: platform                                                
---                                                                                                                                   
apiVersion: v1                  
kind: Namespace                                                                                                                       
metadata:                                                                                                                             
  name: monitoring                                                                                                                    
  labels:                                                                                                                             
    name: monitoring                                              
---                                                                                                                                   
apiVersion: v1                                                    
kind: Namespace                                                
metadata:                                                      
  name: ingress                                                
  labels:                                                      
    name: ingress
