apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oracle
resources:
  - deployment.yaml
  - ghcr-secret.external-secret.yaml
  - migration-job.yaml
  - migrations-configmap.yaml
  - namespace.yaml
  - oracle-db.external-secret.yaml
  - postgres-statefulset.yaml
commonLabels:
  zave.io/workload: oracle
  zave.io/managed-by: argocd
