apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oracle-db
  namespace: oracle
  labels:
    zave.io/workload: oracle
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: oracle-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tenants/oracle/db
        property: POSTGRES_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: tenants/oracle/db
        property: DATABASE_URL
