apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-aws-auto-unseal.sealed-secret.yaml
  - vault-reader-serviceaccount.yaml
  - clustersecretstore.yaml
  - peer-authentication.yaml
