apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - ghcr-secret.external-secret.yaml
  - listings-ingest-db.externalsecret.yaml
  - listings-ingest-storage.externalsecret.yaml
  - postgres-statefulset.yaml
