---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: listings-ingest-storage
  namespace: listings-ingest
  labels:
    zave.io/workload: listings-ingest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: listings-ingest-storage
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: tenants/listings-ingest/storage
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: tenants/listings-ingest/storage
        property: MINIO_SECRET_KEY
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: tenants/listings-ingest/storage
        property: MINIO_ENDPOINT
