apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: data-pipelines-db
  namespace: data-pipelines
  labels:
    zave.io/workload: data-pipelines
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: data-pipelines-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: tenants/data-pipelines/db
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: tenants/data-pipelines/db
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: tenants/data-pipelines/db
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: tenants/data-pipelines/db
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: tenants/data-pipelines/db
        property: DB_PASSWORD
    - secretKey: DB_SSLMODE
      remoteRef:
        key: tenants/data-pipelines/db
        property: DB_SSLMODE
