apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-admin
  namespace: platform
  labels:
    zave.io/workload: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: airflow-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: platform/services/airflow/admin
        property: ADMIN_PASSWORD
    - secretKey: username
      remoteRef:
        key: platform/services/airflow/admin
        property: ADMIN_USERNAME