apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-webserver-secret-key
  namespace: platform
  labels:
    zave.io/workload: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: airflow-webserver-secret-key
    creationPolicy: Owner
  data:
    - secretKey: webserver-secret-key
      remoteRef:
        key: platform/services/airflow/webserver-secret-key
        property: webserver-secret-key
