apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - helmrepository.yaml
  - airflow-db.externalsecret.yaml
  - airflow-fernet.externalsecret.yaml
  - airflow-webserver-secret-key.externalsecret.yaml
  - helmrelease.yaml
  - rbac.yaml
