apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-db
  namespace: platform
  labels:
    zave.io/workload: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: airflow-db
    creationPolicy: Owner
  data:
    - secretKey: connection
      remoteRef:
        key: platform/airflow/db
        property: DATABASE_URL
