apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-fernet
  namespace: platform
  labels:
    zave.io/workload: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: airflow-fernet
    creationPolicy: Owner
  data:
    - secretKey: fernet-key
      remoteRef:
        key: platform/airflow/fernet
        property: FERNET_KEY
