apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-virtualservice.yaml
  - alloy-receiver/
  - alloy-hook-support/
  - ../vault/
  - ../policies/kyverno/

  # ArgoCD platform resources and tenant Application registrations
  - ../argocd/
