apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alloy-receiver-to-tempo-otlp
  namespace: tempo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: alloy
          podSelector:
            matchLabels:
              app.kubernetes.io/name: alloy-receiver
      ports:
        - port: 4317
          protocol: TCP
