apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rigoberta

resources:
  - namespace.yaml
  - ghcr-secret.external-secret.yaml
  - rigoberta-app.external-secret.yaml
  - rigoberta-db.external-secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  zave.io/workload: rigoberta
  zave.io/managed-by: argocd
