apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rigoberta-db
  namespace: rigoberta
  labels:
    zave.io/workload: rigoberta
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: rigoberta-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: tenants/rigoberta/db
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: tenants/rigoberta/db
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: tenants/rigoberta/db
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: tenants/rigoberta/db
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: tenants/rigoberta/db
        property: DB_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: tenants/rigoberta/db
        property: DATABASE_URL
