apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rigoberta-app
  namespace: rigoberta
  labels:
    zave.io/workload: rigoberta
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: rigoberta-app
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: tenants/rigoberta/app
        property: SECRET_KEY_BASE
    - secretKey: REDIS_URL
      remoteRef:
        key: tenants/rigoberta/app
        property: REDIS_URL
