apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: alloy-receiver
  namespace: alloy
  labels:
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/part-of: alloy
spec:
  nameOverride: alloy-receiver
  crds:
    create: false
  serviceAccount:
    create: true
    automountServiceAccountToken: false
  alloy:
    configMap:
      create: false
      name: alloy-receiver
      key: config.alloy
    enableHttpServerPort: true
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
        appProtocol: http
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  controller:
    type: deployment
    replicas: 1
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations:
      k8s.grafana.com/logs.job: integrations/alloy
