apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - alloy.yaml
  - networkpolicy-mia-otlp.yaml
  - networkpolicy-prometheus-scrape.yaml
  - networkpolicy-tempo-export.yaml
  - servicemonitor.yaml
