apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-registry
  namespace: argocd
  labels:
    zave.io/component: argocd
    zave.io/tier: platform-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: private-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: platform/ghcr
        property: .dockerconfigjson

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-keycloak-oidc
  namespace: argocd
  labels:
    zave.io/component: argocd
    zave.io/tier: platform-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: argocd-keycloak-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/name: argocd-keycloak-oidc
          app.kubernetes.io/part-of: argocd
          zave.io/component: argocd
          zave.io/tier: platform-service
      type: Opaque
      data:
        clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: platform/services/argocd/oidc
        property: clientSecret
