---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minio-operator
  namespace: bigbang
spec:
  interval: 10m
  url: https://repo1.dso.mil/big-bang/product/packages/minio-operator.git
  ref:
    tag: 7.1.1-bb.4
