apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository-minio-operator.yaml
  - gitrepository-minio.yaml
  - helmrelease-minio-operator.yaml
  - helmrelease-minio.yaml
  - minio-root-credentials.externalsecret.yaml
  - private-registry.externalsecret.yaml

configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: bigbang-minio-operator-values
    namespace: bigbang
    files:
      - values.yaml=values-minio-operator.yaml
  - name: bigbang-minio-values
    namespace: bigbang
    files:
      - values.yaml=values-minio.yaml
