---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: minio-root-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config.env: |
          export MINIO_ROOT_USER={{ .accesskey }}
          export MINIO_ROOT_PASSWORD={{ .secretkey }}
  data:
    - secretKey: accesskey
      remoteRef:
        key: platform/minio/root
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: platform/minio/root
        property: secretkey
