apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: panchito

resources:
  - namespace.yaml
  - ghcr-secret.external-secret.yaml
  - panchito-app.external-secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  zave.io/workload: panchito
