apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: panchito-app
  namespace: panchito
  labels:
    zave.io/workload: panchito
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: panchito-app
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: tenants/panchito/app
        property: SECRET_KEY
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: tenants/panchito/app
        property: CELERY_BROKER_URL
    - secretKey: CELERY_RESULT_BACKEND
      remoteRef:
        key: tenants/panchito/app
        property: CELERY_RESULT_BACKEND
    - secretKey: LOG_LEVEL
      remoteRef:
        key: tenants/panchito/app
        property: LOG_LEVEL
