apiVersion: v1
kind: Service
metadata:
  name: __WORKLOAD__-canary
  namespace: __NAMESPACE__
  labels:
    app: __WORKLOAD__-canary
    app.kubernetes.io/name: __WORKLOAD__
    app.kubernetes.io/component: canary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 18789
    protocol: TCP
    name: http
  selector:
    app: __WORKLOAD__-canary
