---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgAg7BxAr7QD3z8cDaDToTEDTvar3tfG4NSgpXdXQhIXmvfFJGLVFsBKxXOoPQtJb7g9fjgyTxJ9bBW/2ufoc0KX0RCwrGbPGunDCNiOCBVXJjM5JPLvqkvaxbsfX3b4m3ri8vwsqRe8JUyy5DR1tFmxG9lMj3FBkhS22OS9b1k/16M2Y1ecX9P7C3hOpt2o4FG5cR6QqQ8Wg/1yHZed7d+5lL1VG6XOeSqeo0tKpS4q00JBrQDVrsmTl6SxeumNyPsYO353cz3i9qA1UjYLPWDrf8yG8IrNAfeFONMYBOqAFK5I7jsMTELwILNd+LKOYEDizKQhMc40T4R2tA+M0Bx0Ln1KZqlgQFxfsvDaUspdtO3vSw1tjAxisMzz7i0f/JPPnmW89Wmpv2WeC93a5spEOVNnT4h+6yAPCWdNW/ybUwnt5XrZXqA2HLRv+M2J3sJXvQIF0yMtxQIygo90AATQa9GtZtbBS7MLMgSU9UTYOVZOY8HmDqXlw9YEA3H+7fn09godpmZZpUOH7iS07BQQCRPijuoGjTYyxuOdkaMDLbPAp/VjBXXTjDqQp6X9gCysmWZYz2CjGrctk3QBrTIfEtjYsExPRxAaDsUEacF1tftyAgKs3MQURjBRVUeRNGsL7Yon0vD8mfgDfVEXPDCV72/xtN+B43my2VcoDSEutFQ+Fs7gJc7mI94DpjISG1/P2yEgPUB4douvBEPqGS5w5QgXVNZhNDASZjPtiYMiqBStzZXa7oLZnl5/65sJonnu8Rnsym9M+s6ET+D06ybfnq2rjTqz9OI4elOrMb/sUO4wdzwhj5kGTNnh6z2ZrUB7Qodo24pHdvDcVAUayTD0SkC1emy694sksbVXuF6X09746B0Cy+yCjtirv5oA
  template:
    metadata:
      name: ghcr-secret
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
