apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-required-labels
spec:
  rules:
    - name: inject-name-and-version
      match:
        any:
          - resources:
              kinds:
                - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(app.kubernetes.io/name): "{{ request.object.metadata.labels.app || request.object.metadata.labels.release || 'unknown' }}"
              +(app.kubernetes.io/version): "{{ request.object.metadata.labels.version || 'unset' }}"