apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Add ghcr-secret.sealed.yaml after generating a SealedSecret for namespace kyverno.
  - ghcr-secret.external-secret.yaml
  - require-signed-ghcr-images.yaml
