apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-signed-ghcr-images
spec:
  validationFailureAction: Audit # change to Enforce after validation
  background: true
  rules:
    - name: verify-ghcr-signature-keyless
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/zavestudios/*"
          mutateDigest: false
          imageRegistryCredentials:
            helpers:
              - github
            secrets:
              - ghcr-secret
          attestors:
            - entries:
                - keyless:
                    issuer: "https://token.actions.githubusercontent.com"
                    subjectRegExp: "https://github.com/zavestudios/.+"
                    rekor:
                      url: "https://rekor.sigstore.dev"
