apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-upstream-add-finalizer
  namespace: alloy
  labels:
    app.kubernetes.io/name: alloy-upstream-add-finalizer
    app.kubernetes.io/part-of: alloy
automountServiceAccountToken: true
