apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mia

resources:
  # Add ghcr-secret.sealed.yaml after generating a SealedSecret for namespace mia.
  - ghcr-secret.sealed.yaml
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - canary-deployment.yaml
  - canary-service.yaml
  - canary-ingress.yaml

commonLabels:
  zave.io/workload: mia
  zave.io/managed-by: argocd
