---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mia-provider
  namespace: mia
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgACHebisdfuCcMx3Mqo0KIgTEXo2o7iyLmwO+qskEMa6/jBZFBG1LOj65TXHS21/I6wNLPCS65uObM5hLf/oIgE7dEKu0nCqqY8NJngdX9WtT43FfxRNDc68pTjLKOK7+DX5fFvHz9EmhmImYCqXocRxED68Vm5RD4RHe7Zq4/CdC0OleZ7cIVa/ytVpS7ENazL/DPzDzHgXh8p2aA+j+k/akYk6GiUp+AbgLjiIPI8TJcWW62jFfajVWQdC0vKlKwlqvfGR6cRujVm1q0zD+5SeUcQDt87t5ShFx6txs3AD4B4B2OHwZ1VpBZ8u1jHPsVVmOwkxzzeZge0tfmokcLLcRqTsMR3JZKAKl6EsHhCfta+vRhBeHlrP4q5ZjAF7WpLWZW/77VODOxtoB/T+Sx/GtzKebgix3voQo7RFHqjjrMdbbTtqKcNArwIGicQxe85gI81WCa4dYrtFWx3z9iHk+eDhwBWiu9pkFpl7LgVQrkQt/GsvM3IZHt+JWmoEWvYRrZ75iMdwEtMVfjrn91+rKfSikIwoVT2bN83ytIqdOt7DYuTKztIWWtLyCl0xY1si+Otlm/XJGNVQ7HGJn7A22NkXDRcW5QUZ/0XwHo4qJs1TmIN1Y2c6eR0LTEvAkbhosGVvvCRGrTB27w5AAwV0vXoGveWbXkaL0dsXWP+O/5vk+rKz8FWHFgRaPtepa9LQgyemuI8ro+123p7hJ9Z0fwi8Ew0OrDaAIzggH90L+Wc9f0M2NThnWXDHp7wUxaiGG2Czt0KFZ6T1CXkfUc7GTfV8f2XioBOorvrd3lWVmIEw/GmvLltCDyK8O4Np7MFzsXwEXUa6QHlWnA=
    OPENAI_API_KEY: AgBxefNsxm3/Eyjvo6I2fS/O8lX8fetCQUcvx/J9TtyaY0WDUJozxw585EULOjP3doMoLXiFjC2LDl4tD6e1LNkzj1C+RQ+A3rkVmgTKHIor8W9/0SI83/4Z8qqSBs7tzCJECQOvrWDZ+4U/di00SuNM69EG3wmuPksO4OZs9QIOZafqEHPGimlA0891tVfmkXjxQUyDKKG7QTUd+pghjGP2u4tiQt7uUcTgVeR5rLqPzUC9zORMvNESx0udufgakXfDPC46CmZ3ObP4ECwsvjPHZ8kZakjTQktmE/2U1bBc3vPJoQMxY/pi25iC4eq4u8KOOvYzNTcWHRrd7PrUZnz/ZCBE5ZFGBks+I54M1kKfpBntQKE0eoDDO6DVQsmMrFY0LW+gsA8nA9r56SvX+KjpVS1nk7DAaBgPihk79r643044AzErCwgedxJvLYO7R6z3fB7QydqTqy4ajwI9zJzqCacOnoIEijDA9Rji1uMU+sE506X+91LVh3gm6xR+jedsBO948wyceJxxCpJhLGVUshwaDEaJvUSZnTA03GkMn+3+OAmZPEIWR8xiSO0hbbZrIeL8ME2YC9HWlLbJ48HO1i4nJneKq18c6i1zZv030xkCFiEB1n5PYpvKXoKpbzmnpayF/RbqkCN9o3kB8ETDYmVuNXYzDFADfjz/u+ySCpTLfvjj/yWm3MU8rCKPvSNs8Uyb534u8KB4mDvUhaKNglV+pl4XmlcMy+SgbIZNgvyeMV2gAOjUW3u2VCH2SwHXC+Yvq6T6nC7W72qRrGRJ8bMBN1f3nDhTu1B4NXe2c7TuD5FknnucgIZjNZn/I/TRo+jbdNcumJYP4o/DE5AjJ5v0LMu6rXCcIYkWfZ3ls2/U6Ha9GiYBotsa2rdaJd8bqYfmnqqyUaIPJShaOUOBQjGZcg8=
  template:
    metadata:
      creationTimestamp: null
      name: mia-provider
      namespace: mia
    type: Opaque
