apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mia-data
  namespace: mia
  labels:
    app: mia
    zave.io/workload: mia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
