apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: mia
  labels:
    app: ollama
    app.kubernetes.io/name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
        app.kubernetes.io/name: ollama
        app.kubernetes.io/version: "0.17.7"
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ollama
        image: ollama/ollama:0.17.7
        ports:
        - containerPort: 11434
          name: http
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: 11434
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 60
        readinessProbe:
          tcpSocket:
            port: 11434
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 11434
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
